version: '3.8'
name: Episode 0 - First Contact with Road Runner
services:
  roadrunner:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - vendor:/app/vendor

volumes:
  vendor: